FROM node:alpine

WORKDIR /usr/src/server

COPY ./package.json ./
RUN npm install && npm cache clean --force
COPY . .

# ENV DATABASE_URL="postgres://root:test@localhost:5432/fallback_flamant"

# RUN node ace migration:run

CMD ["npm", "run", "dev"]